### ISSUE TITLE
Cannot `make run` if you set `$APOLLO_KEY` to a user API key

### ISSUE THREAD

**Issue by EverlastingBugstopper** [apollographql/supergraph-demo#9]
For my local `rover` development, I have `APOLLO_KEY` set to a user API key in my shell profile. 

The default behavior for `apollo-server` is to enable usage reporting if `APOLLO_KEY` is present, but unfortunately it does not work if you set `APOLLO_KEY` to a user API key.

This is already tracked in [this issue](https://github.com/apollographql/apollo-server/issues/4640) on the `apollo-server` repository, but I wanted to also document it here in case someone runs into this problem while trying out the demo.

```console
$ node --version
14.16.0
$ rover config whoami
Checking identity of your API key against the registry.
Key Type: USER
User ID: gh.EverlastingBugstopper
Origin: $APOLLO_KEY
API Key: user************************************************
$ make run
node index.js local
Starting Apollo Gateway in local mode ...
Using local: ./supergraph.graphql
No graph variant provided. Defaulting to `current`.
Error: You've enabled usage reporting via ApolloServerPluginUsageReporting, but you also need to provide your Apollo API key, via the APOLLO_KEY environment variable or via `new ApolloServer({apollo: {key})
    at Object.serverWillStart (/home/avery/work/forks/supergraph-demo/node_modules/apollo-server-core/dist/plugin/usageReporting/plugin.js:62:23)
    at /home/avery/work/forks/supergraph-demo/node_modules/apollo-server-core/dist/ApolloServer.js:261:122
    at Array.map (<anonymous>)
    at ApolloServer.<anonymous> (/home/avery/work/forks/supergraph-demo/node_modules/apollo-server-core/dist/ApolloServer.js:261:73)
    at Generator.next (<anonymous>)
    at fulfilled (/home/avery/work/forks/supergraph-demo/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
$ unset APOLLO_KEY
$ make run
node index.js local
Starting Apollo Gateway in local mode ...
Using local: ./supergraph.graphql
🚀 Server ready at http://localhost:4000/
 ```

**Comment by prasek** [comment]
@EverlastingBugstopper this should be fixed now via #143 which also fixes #136. Note the APOLLO_KEY and APOLLO_GRAPH_REF override behavior by `./graph-api.env` in #143 for your CI usage. 🙂
